version: '3'
services:
  elasticsearch:
    image: a852203465/elasticsearch-ik:7.10.2
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - cluster.name=es-cluster
      - discovery.seed_hosts=elasticsearch
      - cluster.initial_master_nodes=elasticsearch
      - bootstrap.memory_lock=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./data/es01:/usr/share/elasticsearch/data
      - ./logs/es01:/user/share/elasticsearch/logs
    ports:
      - 9200:9200
    networks:
      - es_net

networks:
  es_net:
    external: true


















